name: Find Directories

on:
  push:
    branches: [ main ]

jobs:
  find-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run sudo find
        run: |
          sudo find /
